[project]
name = "python-modules"
version = "0.1.0"
description = "Python modules for YouTuber Helper"
requires-python = ">=3.10"
dependencies = [
    "google-generativeai>=0.8.0",
    "psycopg2-binary>=2.9.9",
    "python-dotenv>=1.0.0",
    "google-genai",
    "boto3",
]
